import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import icon from '../../public/icons/Frame 639.svg'
import Speakers from "@/shared/components/Speakers/page";

export const dudka = localFont({
  src :"./fonts/Dudka.woff2",
  variable: '--font-dudka',
  display: 'swap',
});
export const monsterBeast = localFont({
  src: './fonts/NCLMonsterBeast-Demo.woff2',
  variable: '--font-monster-beast',
  display: 'swap',
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Онкологический центр",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dudka.variable} ${monsterBeast.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
